# Generated by Django 2.1.7 on 2021-07-19 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akash', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
